#!/usr/bin/env python3
"""Generate SIM-LINES-4X metrics table for the paper."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


METRICS = [
    ("mae", "MAE"),
    ("psnr", "PSNR (dB)"),
    ("ssim", "SSIM"),
    ("ms_ssim", "MS-SSIM"),
]


def _format_value(value: float | None) -> str:
    if value is None:
        return "N/A"
    return f"{value:.6f}"


def _metric_pair(metrics: dict, key: str) -> list[float | None]:
    value = metrics.get(key, [None, None])
    if isinstance(value, list):
        return (value + [None, None])[:2]
    return [value, None]


def render_table(data: dict) -> str:
    header_cells = ["Case"]
    for _, label in METRICS:
        header_cells.append(f"{label} (Amp)")
        header_cells.append(f"{label} (Phase)")

    same_split_benchmark = data.get("same_split_cdi_benchmark")
    if same_split_benchmark:
        caption = (
            r"\caption{SIM-LINES-4X reconstruction metrics. The historical "
            r"overlap/probe rows use the stitched test split random subsample "
            r"(nsamples=1000, seed=7). The same-split comparator block reports "
            r"the accepted generated-split PyNX HIO/ER/PtychoPINN benchmark over "
            r"2178 test frames under the direct-stitch, known-probe "
            r"support-threshold 0.05 contract and is not historical Table 2 "
            r"compatible (\texttt{table2\_compatible=false}). Phase FRC50 is "
            r"undefined because the ground-truth phase is constant zero.}"
        )
    else:
        caption = (
            r"\caption{SIM-LINES-4X reconstruction metrics on the stitched test split. "
            r"Ground truth uses the simulated object, cropped to the scanned region via "
            r"scan-coordinate alignment. Test evaluation uses a random subsample "
            r"(nsamples=1000, seed=7). Phase FRC50 is undefined because the "
            r"ground-truth phase is constant zero.}"
        )

    lines = [
        "% Generated by tables/scripts/generate_sim_lines_4x_metrics.py",
        "% Source: data/sim_lines_4x_metrics.json (eval_reconstruction outputs)",
        r"\begin{table}[htbp]",
        r"\centering",
        caption,
        r"\label{tab:sim_lines_metrics}",
        r"\begin{tabular}{@{}l" + "c" * (len(header_cells) - 1) + r"@{}}",
        r"\toprule",
        " & ".join(header_cells) + r" \\",
        r"\midrule",
    ]

    for case in data["cases"]:
        row = [case["label"]]
        metrics = case["metrics"]
        for metric_key, _ in METRICS:
            amp_val, phase_val = metrics[metric_key]
            row.append(_format_value(amp_val))
            row.append(_format_value(phase_val))
        lines.append(" & ".join(row) + r" \\")

    if same_split_benchmark:
        lines.append(r"\midrule")
        lines.append(
            rf"\multicolumn{{{len(header_cells)}}}{{@{{}}l}}{{Same-split experimental-probe benchmark}} \\"
        )
        for row_data in same_split_benchmark.get("rows", []):
            row = [row_data["label"]]
            metrics = row_data.get("metrics", {})
            for metric_key, _ in METRICS:
                amp_val, phase_val = _metric_pair(metrics, metric_key)
                row.append(_format_value(amp_val))
                row.append(_format_value(phase_val))
            lines.append(" & ".join(row) + r" \\")

    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}"])
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("paper/data/sim_lines_4x_metrics.json"),
        help="Input JSON metrics file.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("paper/tables/sim_lines_4x_metrics.tex"),
        help="Output LaTeX table path.",
    )
    args = parser.parse_args()

    data = json.loads(args.input.read_text(encoding="utf-8"))
    output = render_table(data)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
